import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def plot_null_group(df, prefix, title_main, p_color, bf_color):
    # Skip if the CSV doesn't contain data for this null (e.g., unnamed MBA was skipped)
    if f'{prefix}_p' not in df.columns or df[f'{prefix}_p'].isnull().all():
        print(f"Skipping {title_main} - no data found.")
        return

    # Create figure with two polar subplots (p-value and Bayes Factor)
    fig, (ax1, ax2) = plt.subplots(1, 2, subplot_kw={'projection': 'polar'}, figsize=(16, 7))
    fig.suptitle(title_main, fontsize=18, fontweight='bold', y=1.08)
    
    theta = np.deg2rad(df['direction_deg'])
    
    # Illustrative angular landmarks (Conjunction, Squares, Opposition)
    tick_angles = np.deg2rad([0, 45, 90, 135, 180, 225, 270, 315])
    tick_labels = [
        '0°\n(Conjunction)', '45°', '90°\n(Square)', '135°', 
        '180°\n(Opposition)', '225°', '270°\n(Square)', '315°'
    ]

    # ---------------------------------------------------------
    # Subplot 1: P-Value
    # ---------------------------------------------------------
    ax1.plot(theta, df[f'{prefix}_p'], color=p_color, linewidth=2.5, label='Observed p-value')
    ax1.set_title('Omnibus Significance (p-value)\nLower / Closer to center = More Significant', 
                  va='bottom', pad=20, fontsize=13)
    ax1.set_theta_zero_location("N") # 0 degrees at top
    ax1.set_theta_direction(-1)      # Clockwise
    ax1.set_xticks(tick_angles)
    ax1.set_xticklabels(tick_labels, fontsize=10, fontweight='bold')
    
    # Red dashed threshold ring for p=0.05
    ax1.plot(np.linspace(0, 2*np.pi, 100), [0.05]*100, 
             color='red', linestyle='--', linewidth=1.5, label='p = 0.05 threshold')
    
    # Move radial labels so they don't block the 0-degree line
    ax1.set_rlabel_position(22.5) 
    ax1.legend(loc='upper right', bbox_to_anchor=(1.35, 1.1))

    # ---------------------------------------------------------
    # Subplot 2: Bayes Factor
    # ---------------------------------------------------------
    ax2.plot(theta, df[f'{prefix}_bf'], color=bf_color, linewidth=2.5, label='Bayes Factor')
    ax2.set_title('Evidence Strength (Bayes Factor)\nHigher / Further out = Stronger Evidence', 
                  va='bottom', pad=20, fontsize=13)
    ax2.set_theta_zero_location("N") 
    ax2.set_theta_direction(-1)      
    ax2.set_xticks(tick_angles)
    ax2.set_xticklabels(tick_labels, fontsize=10, fontweight='bold')
    
    # Orange and Red threshold rings for standard Jeffreys scale cutoffs
    ax2.plot(np.linspace(0, 2*np.pi, 100), [10]*100, 
             color='orange', linestyle='--', linewidth=1.5, label='BF = 10 (Strong)')
    ax2.plot(np.linspace(0, 2*np.pi, 100), [30]*100, 
             color='red', linestyle='--', linewidth=1.5, label='BF = 30 (Very Strong)')
    
    ax2.set_rlabel_position(22.5)
    ax2.legend(loc='upper right', bbox_to_anchor=(1.35, 1.1))

    # Save and output
    filename = f"{prefix}_vtest_polar_plot.png"
    plt.savefig(filename, dpi=200, bbox_inches='tight')
    print(f"Saved {title_main} plot to -> {filename}")

def main():
    try:
        # Load the omnibus data generated by conjunction_vtest_360.py
        df = pd.read_csv("conjunction_vtest_omnibus.csv")
    except FileNotFoundError:
        print("Error: 'conjunction_vtest_omnibus.csv' not found. "
              "Please run this in the directory where your CSV is saved.")
        return

    # Plot 1: Compound Null (Phase shift + Date swap)
    # Using Blue for p-value and Green for Bayes factor
    plot_null_group(df, 'cmp', 'Compound Null (Phase-Shift) vs. Observation', 
                    p_color='#1f77b4', bf_color='#2ca02c')

    # Plot 2: Unnamed-MBA Null (Named vs. Unnamed contrast)
    # Using Purple for p-value and Orange for Bayes factor
    plot_null_group(df, 'mba', 'Unnamed-MBA Null vs. Observation', 
                    p_color='#9467bd', bf_color='#ff7f0e')

if __name__ == "__main__":
    main()